Header
001elijah/bc-48-html-project-3 pull request #17
Opened 2023-01-29 16:53 UTC by OlegatorIT

2023-01-29 20:26 UTC, adventuretimedi reviewed
Hi Oleg, reviewed.

2023-01-30 00:07 UTC, BohdanChurevych submitted a review, later dismissed
+

2023-01-30 10:17 UTC, 001elijah requested changes
перевірив. є нюанси. очікую виправлення

2023-01-30 10:17 UTC, 001elijah commented on src/partials/header.html
> +    <div class=" header-box container ">
`помісти container в окремий div, після тегу <header>`

2023-01-30 10:17 UTC, 001elijah commented on src/partials/header.html
> +            <svg class="menu-open" width="23.33" height="16.41">
в тебе дублюються ці ж width і height в _header.scss. залиш або тільки тут, або тільки там.

2023-01-30 10:25 UTC, OlegatorIT commented on src/partials/header.html
> +    <div class=" header-box container ">
навіщо плодити додатковий дів ?

2023-01-30 10:27 UTC, adventuretimedi reviewed
Reviewed!

2023-01-30 10:27 UTC, OlegatorIT commented on src/partials/header.html
> +            <svg class="menu-open" width="23.33" height="16.41">
не працює так якщо ставити тільки в нтмл розмір не той

2023-01-30 10:31 UTC, 001elijah commented on src/partials/header.html
> +    <div class=" header-box container ">
це для однородності проекту в цілому. може бути й так в принципі, аби не було конфліктів у цих класів

2023-01-30 10:32 UTC, 001elijah commented on src/partials/header.html
> +            <svg class="menu-open" width="23.33" height="16.41">
добре, хай буде

2023-01-30 10:41 UTC, merged